# Column glossary for CRM / Sales Opportunities and Ticket / Incident Management schemas.
# Used to give the LLM accurate column descriptions so it selects the right columns
# for SQL and visualizations. Keys are uppercase column names (spaces allowed) for case-insensitive lookup.
# Lookup also tries underscore variant (e.g. Ticket_ID -> TICKET ID).

COLUMN_GLOSSARY = {
    "OPP_SOL_NO": "Opportunity solution number; unique identifier for the opportunity record",
    "FETCH_TIMESTAMP": "When the data was fetched or last synced from source system",
    "OPP_NUMBER": "Opportunity number; external or display ID for the opportunity",
    "IFI_ACCOUNT": "IFI (Internal/Institutional) account identifier",
    "KPMG_STATUSREASON": "KPMG-specific status reason for the opportunity",
    "SALESSTAGECODE": "Sales stage code (e.g. pipeline stage code); use with SALESSTAGECODE_VALUE for label",
    "PROPOSAL_VALUE_INC_SUCCESS_FEE": "Proposal value including success fee; monetary amount",
    "NFR_CY": "Net fee revenue current year",
    "NFR_CY1": "Net fee revenue current year +1",
    "NFR_CY2": "Net fee revenue current year +2",
    "NFR_CY3": "Net fee revenue current year +3",
    "NFR_CY4": "Net fee revenue current year +4",
    "NFR_PY": "Net fee revenue prior year",
    "SUCCESSFEE_AMOUNT": "Success fee amount; monetary",
    "TAXONOMY": "Taxonomy or classification of the opportunity",
    "COMPETITOR": "Competitor name or identifier",
    "STRATEGIC_SOLUTION": "Strategic solution type or name",
    "AUDIT_ROTATEOUT": "Audit rotate-out indicator or date",
    "SOLUTIONCLOSEDATE": "Date when the solution/opportunity was closed",
    "CONFIDENTIAL": "Confidentiality flag or level",
    "KPMG_PROJECTACCOUNT": "KPMG project account code or ID",
    "TOPIC": "Topic or subject of the opportunity",
    "SYSTEM_REASON_FOR_WIN_LOSS": "System-captured reason for win or loss",
    "SALES_CREDIT_TO_SOLUTION_ARCHITECT": "Sales credit amount allocated to solution architect",
    "SALES_CREDIT_TO_ARD_BDM": "Sales credit amount allocated to ARD BDM",
    "SALES_CREDIT_PERCENTAGE_1_ENGAGEMENTMANAGER": "Sales credit percentage for engagement manager (1)",
    "SALES_CREDIT_PERCENTAGE_3": "Sales credit percentage (3)",
    "SALES_CREDIT_PERCENTAGE_4": "Sales credit percentage (4)",
    "SALES_CREDIT_PERCENTAGE_5": "Sales credit percentage (5)",
    "SALES_CREDIT_PERCENTAGE_6": "Sales credit percentage (6)",
    "SALESSTAGE": "Sales stage name or label (e.g. Qualify, Propose, Won)",
    "KPMG_REASON": "KPMG reason code or description",
    "CREATEDON": "Record creation date/time",
    "MODIFIEDON": "Record last modified date/time",
    "LOCATION": "Location name or code",
    "GCC": "GCC (e.g. geography/country code) or region code",
    "GP": "GP (e.g. practice or group) code",
    "NET_RATE_PER_HOUR": "Net rate per hour; numeric",
    "WIN_LOSS_MODIFIED_DATE": "Date when win/loss status was last modified",
    "PROPOSAL_SUBMISSION_DATE": "Date when proposal was submitted",
    "ONHOLD_END_DATE": "Date when opportunity was taken off hold",
    "OPPORTUNITY_NATURE": "Nature of opportunity (e.g. new, renewal)",
    "ALLIANCE_ORG": "Alliance organization",
    "PROJECT_CODE": "Project code",
    "CLIENT_CONTACT_NAME": "Client contact person name",
    "CLIENT_CONTACT_DESIGNATION": "Client contact job title/designation",
    "IG_CATEGORY": "Industry group category",
    "SENTINEL_NUMBER": "Sentinel reference number",
    "PRIMARY_INDUSTRY_GROUP": "Primary industry group",
    "CLIENTNAME": "Client name",
    "ACCOUNTNUMBER": "Account number",
    "SECONDARY_INDUSTRY": "Secondary industry",
    "CORRIDOR2": "Corridor 2 (e.g. segment or region)",
    "GOV_CHANNEL": "Government channel indicator",
    "PSU": "PSU (public sector unit) indicator",
    "PRIMARY_REGION": "Primary region",
    "PRIMARYINDUSTRYSUBGROUP": "Primary industry subgroup",
    "REKONNECT_PC_CODE": "Rekonnect profit center code",
    "ULTIMATE_CLIENT_NAME": "Ultimate parent client name",
    "CLIENT_GROUP_NAME": "Client group name",
    "KPMG_PROJECTACCOUNT_NAME": "KPMG project account name",
    "CRM_STATUS": "CRM status (e.g. Open, Won, Lost)",
    "PURSUITOWNER": "Pursuit owner name",
    "PURSUITOWNER_EMAILID": "Pursuit owner email",
    "ORIGINATOR_1": "Originator 1 name",
    "ORIGINATOR_1_EMAILID": "Originator 1 email",
    "ORIGINATOR_2": "Originator 2 name",
    "ORIGINATOR_2_EMAILID": "Originator 2 email",
    "SOLUTION_ARCHITECT": "Solution architect name",
    "SOLUTION_ARCHITECT_EMAILID": "Solution architect email",
    "SALES_CREDIT_VALUE_TO_SOLUTION_ARCHITECT": "Sales credit value for solution architect",
    "ARD_BDM": "ARD BDM name",
    "ARD_BDM_EMAILID": "ARD BDM email",
    "SALES_CREDIT_VALUE_TO_ARD_BDM": "Sales credit value for ARD BDM",
    "SEC_REGION": "Secondary region",
    "TER_REGION": "Tertiary region",
    "TEAMMEMBER1_ENGAGEMENTMANAGER_EMAILID": "Engagement manager 1 email",
    "TEAMMEMBER1_ENGAGEMENTMANAGER": "Engagement manager 1 name",
    "SALES_CREDIT_VALUE_2": "Sales credit value (2)",
    "TEAMMEMBER2": "Team member 2 name",
    "TEAMMEMBER2_EMAILID": "Team member 2 email",
    "SALES_CREDIT_PERCENTAGE_2": "Sales credit percentage (2)",
    "TEAMMEMBER3": "Team member 3 name",
    "TEAMMEMBER3_EMAILID": "Team member 3 email",
    "SALES_CREDIT_VALUE_3": "Sales credit value (3)",
    "TEAMMEMBER4": "Team member 4 name",
    "TEAMMEMBER4_EMAILID": "Team member 4 email",
    "SALES_CREDIT_VALUE_4": "Sales credit value (4)",
    "TEAMMEMBER5": "Team member 5 name",
    "TEAMMEMBER5_EMAILID": "Team member 5 email",
    "SALES_CREDIT_VALUE_5": "Sales credit value (5)",
    "TEAMMEMBER6": "Team member 6 name",
    "TEAMMEMBER6_EMAILID": "Team member 6 email",
    "SALES_CREDIT_VALUE_6": "Sales credit value (6)",
    "SALESSTAGECODE_VALUE": "Sales stage code value or display label (use with SALESSTAGECODE)",
    "PROBABILITY": "Win probability; numeric percentage or decimal",
    "CORRIDOR1": "Corridor 1 (segment/region)",
    "CORRIDOR3": "Corridor 3 (segment/region)",
    "COUNTRY": "Country name or code",
    "REASON_FOR_WIN_LOSS": "Reason for win or loss",
    "MONTH_CHANGE_OF_STATUS": "Month when status last changed",
    "FUNCTIONAL_AREA": "Functional area",
    "SERVICE_GROUP": "Service group",
    "SERVICELINE": "Service line",
    "PROFITCENTER": "Profit center code or name",
    "SFACCRUEDDATE": "Success fee accrued date",
    "SOLUTION": "Solution name or type",
    "PRIMARY_INDUSTRY": "Primary industry",
    "TERTIARY_INDUSTRY": "Tertiary industry",
    "SECONDARY_INDUSTRY_SUB_GROUP": "Secondary industry sub group",
    "TERTIARY_INDUSTRY_SUB_GROUP": "Tertiary industry sub group",
    "SECONDARY_INDUSTRY_GROUP": "Secondary industry group",
    "TERTIARY_INDUSTRY_GROUP": "Tertiary industry group",
    "SECTOR1": "Sector 1",
    "SECTOR2": "Sector 2",
    "SECTOR3": "Sector 3",
    "PROJECT_INDUSTRY_1": "Project industry 1",
    "PROJECT_INDUSTRY_2": "Project industry 2",
    "PROJECT_SEC1": "Project sector 1",
    "PROJECT_SEC2": "Project sector 2",
    "AGEING": "Ageing (e.g. days open or age bucket)",
    "OPP_CLOSURE_DATE": "Opportunity closure date",
    "OPP_CLOSURE_YEAR": "Opportunity closure year",
    "OPP_CLOSURE_MONTH": "Opportunity closure month",
    "OPP_CLOSURE_FY": "Opportunity closure fiscal year",
    "OPP_CREATION_YEAR": "Opportunity creation year",
    "OPP_CREATION_MONTH": "Opportunity creation month",
    "OPP_CREATION_FY": "Opportunity creation fiscal year",
    "SUBLOB": "Sub line of business",
    "LOB": "Line of business",
    "INFLUENCING_CORRIDOR": "Influencing corridor",
    "IG_COUNTRY": "Industry group country",
    "SALES_CREDIT_VALUE_1": "Sales credit value (1)",
    "OPE": "OPE (e.g. operating metric) code or value",
    "MANAGEDSERVICE": "Managed service indicator or name",
    "FEES": "Fees amount",
    "ESTIMATEDCLOSEDATE": "Estimated close date",
    "MODIFIEDBY": "User who last modified the record",
    "CLIENTEMAIL": "Client email",
    "CLOUDRELATED": "Cloud-related indicator",
    "ALLIANCEDETAILS": "Alliance details",
    "ALLIANCE": "Alliance name or code",
    "REMAININGSUCCESSFEE": "Remaining success fee amount",
    "INDIAHEADOFFICE": "India head office indicator or name",
    "IFI_FUNDED": "IFI funded indicator",
    "PROJECTSELECTION": "Project selection",
    "IFI_ACCOUNT_GUID": "IFI account GUID",
    "LOCATION_GUID": "Location GUID",
    "CYACCRUEDSUCCESSFEE": "Current year accrued success fee",
    "ULTIMATE_CLIENT_ACCOUNT_NUMBER": "Ultimate client account number",
    "OEM": "OEM (original equipment manufacturer) or partner",
    "LEAD_PARTNER_1": "Lead partner 1 name",
    "LEAD_PARTNER_1_EMAILID": "Lead partner 1 email",
    "LEAD_PARTNER_2": "Lead partner 2 name",
    "LEAD_PARTNER_2_EMAILID": "Lead partner 2 email",
    "INVOLVEMENT_LEAD_PARTNER_1": "Involvement lead partner 1",
    "INVOLVEMENT_LEAD_PARTNER_2": "Involvement lead partner 2",
    "MARKETS_PARTNER_1": "Markets partner 1 name",
    "MARKETS_PARTNER_1_EMAILID": "Markets partner 1 email",
    "MARKETS_PARTNER_2": "Markets partner 2 name",
    "MARKETS_PARTNER_2_EMAILID": "Markets partner 2 email",
    "INVOLVEMENT_MARKETS_PARTNER_1": "Involvement markets partner 1",
    "INVOLVEMENT_MARKETS_PARTNER_2": "Involvement markets partner 2",
    # ─── Ticket / Incident Management schema ───
    "TICKET ID": "Unique ticket or incident identifier",
    "ENCRIPTED TICKET ID": "Encrypted ticket ID for secure reference",
    "TICKET NO": "Ticket number; display or reference number",
    "REGISTERED TIME": "When the ticket was registered or created",
    "STATUS": "Current ticket status (e.g. Open, In Progress, Resolved, Closed)",
    "MEDIUM": "Channel or medium through which ticket was raised (e.g. email, phone, portal)",
    "DESCRIPTION": "Ticket description or summary",
    "RESPONSE DEADLINE": "Date/time by which first response is due",
    "RESPONSE TIME": "When the first response was made",
    "RESPONSE SLA MET": "Whether response SLA was met (yes/no or flag)",
    "RESPONSE SLA REASON": "Reason if response SLA was not met",
    "RESOLUTION DEADLINE": "Date/time by which resolution is due",
    "RESOLUTION TIME": "When the ticket was resolved",
    "RESOLUTION SLA MET": "Whether resolution SLA was met",
    "RESOLUTION SLA REASON": "Reason if resolution SLA was not met",
    "REOPEN TICKET": "Whether ticket was reopened (flag or count)",
    "ESCALATION RESPONSED": "Whether escalation was responded to",
    "UPDATED TIME": "When the ticket was last updated",
    "REVIEWED": "Whether ticket was reviewed",
    "SCHEDULE DATE": "Scheduled date for work",
    "TARGET COMPLETION DATE": "Target date for completion",
    "MANUAL ESCALATION DATE": "Date when manually escalated",
    "MANUAL ESCALATION REMARKS": "Remarks for manual escalation",
    "NOTIFICATION METHOD": "How notifications are sent",
    "RESPONSE ELAPSETIME": "Elapsed time to first response (e.g. minutes)",
    "RESOLUTION ELAPSETIME": "Elapsed time to resolution",
    "CLOSURE DATE": "Date when ticket was closed",
    "FCR TICKET": "First contact resolution ticket indicator",
    "FCR COMMENTS": "First contact resolution comments",
    "RESPONSE DEADLINEMINUTES": "Response deadline in minutes",
    "CALLER UPDATE": "Update from caller",
    "FCR MET": "Whether first contact resolution was met",
    "SOURCE": "Source of the ticket (e.g. portal, email, phone)",
    "CONVERTED TO SR": "Converted to service request reference",
    "CONVERTED TYPE": "Type of conversion",
    "CHILD INCIDENT COUNT": "Number of child incidents",
    "SUP FUNCTION": "Support function code",
    "SUP FUNCTION NAME": "Support function name",
    "CUSTOMER": "Customer name or identifier",
    "LOCATION": "Location name or code",
    "LOGGED BY USER ID": "User ID of person who logged the ticket",
    "LOGGED BY USER NAME": "Name of person who logged the ticket",
    "LOGGED BY EMPID": "Employee ID of person who logged",
    "LOGGED BY EMAIL": "Email of person who logged",
    "LOGGED BY MOBILE": "Mobile of person who logged",
    "LOGGED BY CONTACT": "Contact of person who logged",
    "CALLER USER ID": "Caller user ID",
    "CALLER EMPLOYEE ID": "Caller employee ID",
    "CALLER USER NAME": "Caller user name",
    "CALLER EMAIL": "Caller email",
    "CALLER MOBILE": "Caller mobile",
    "CALLER CONTACT": "Caller contact number",
    "CALLER DESIGNATION": "Caller job designation",
    "CLASSIFICATION": "Ticket classification (e.g. type or category code)",
    "CATEGORY": "Ticket category",
    "PENDING REASON": "Reason ticket is pending",
    "SEVERITY NAME": "Severity name (e.g. Critical, High, Medium, Low)",
    "SEVERITY DISPLAY": "Severity display label",
    "CRITICALITY": "Criticality level",
    "SLA NAME": "SLA agreement name",
    "WORKGROUP NAME": "Workgroup or team name",
    "ASSIGNED ENGINEER USERID": "Assigned engineer user ID",
    "ASSIGNED ENGINEER UNAME": "Assigned engineer user name",
    "ASSIGNED ENGINEER EMPID": "Assigned engineer employee ID",
    "ASSIGNED ENGINEER EMAIL": "Assigned engineer email",
    "CLOSURE CODE": "Closure code or reason",
    "RESOLUTION CODE": "Resolution code or type",
    "CUSTOMER MATRIX MASTERID": "Customer matrix master ID",
    "RESPONSE SLA MINS": "Response SLA in minutes",
    "RESOLUTION SLA MINS": "Resolution SLA in minutes",
    "RESPONSE WG ID": "Response workgroup ID",
    "RESPONSE EX ID USERID": "Response assignee user ID",
    "RESPONSE EX ID UNAME": "Response assignee user name",
    "RESPONSE EX ID EMPID": "Response assignee employee ID",
    "RESPONSE EX ID EMAIL": "Response assignee email",
    "FIRST WORKGROUP NAME": "First workgroup name",
    "RESPONSE PRIORITY NAME": "Response priority name",
    "RESPONSE PRIORITY SLA": "Response priority SLA",
    "RESPONSE PRIORITY RESOLUTION SLA": "Response priority resolution SLA",
    "TEMPLATE NAME": "Template name used for ticket",
    "TEMPLATE SYMPTOM": "Template symptom description",
    "OPEN CATEGORY": "Category when ticket was open",
    "CONVERTED SR TICKET NUMBER": "Converted service request ticket number",
    "PARTNER ID": "Partner identifier",
    "PCONTACT": "Partner contact",
    "PTICKET ID": "Parent or partner ticket ID",
    "PTICKET SEVERITY": "Parent/partner ticket severity",
    "PTICKET SOLUTION": "Parent/partner ticket solution",
    "PTICKET STATUS": "Parent/partner ticket status",
    "INFORMATION": "Additional information",
    "SOLUTION": "Resolution or solution text",
    "IMPACT NAME": "Impact name or description",
    "TOTAL PENDING DURATION SLA MINUTES": "Total pending duration within SLA in minutes",
    "TOTAL PENDING DURATION": "Total time ticket was in pending state",
    "LAST USER COMMUNICATION": "Last communication from user",
    "PRIVATE LOG": "Private log or internal notes",
    "RESOLUTION SLA MET WITH PENDING": "Whether resolution SLA was met including pending time",
    "LINK KB ON TICKET RESOLVE": "KB article linked on resolve",
    "CUSTOMER CONTRACT ID": "Customer contract identifier",
    "WORKGROUP ASSIGNED TIME": "When workgroup was assigned",
    "STATUS WHILE WORKGROUP CHANGED": "Status when workgroup was changed",
    "ANALYST ASSIGNED TIME": "When analyst was assigned",
    "STATUS WHILE ANALYST CHANGED": "Status when analyst was changed",
    "RESOLVED UPDATED BY USERID": "User ID who last updated resolution",
    "RESOLVED UPDATED BY USER NAME": "User name who last updated resolution",
    "RESOLVED UPDATED BY EMAILID": "Email of user who last updated resolution",
    "CATEGORY ID": "Category identifier",
    "CLASSIFICATION ID": "Classification identifier",
    "IS ATTACHMENTS AVAILABLE": "Whether attachments are available (yes/no)",
    "IS KB AVAILABLE": "Whether KB article is available",
    "IS AUTO ESCALATED": "Whether ticket was auto-escalated",
    "IS MANUAL ESCALATED": "Whether ticket was manually escalated",
    "TICKET CLOSING MODE": "Mode in which ticket was closed",
    "IS UNASSIGNED STATUS ESCALATED": "Whether unassigned status was escalated",
    "IS PENDING STATUS ESCALTED": "Whether pending status was escalated",
    "SECONDARY ASSIGNED ENGINEER USER ID": "Secondary assigned engineer user ID",
    "IS FEEDBACK ENABLED": "Whether feedback is enabled",
    "IS REASSIGNED ESCALATED": "Whether reassignment was escalated",
    "RESOLUTION DEADLINE MINUTES": "Resolution deadline in minutes",
    "IS ETR ESCALATED": "Whether ETR (estimated time to resolve) was escalated",
    "FOLLOWUP CALL COUNT": "Number of follow-up calls",
    "IS ENABLED FOLLOWUP": "Whether follow-up is enabled",
    "PARENT TICKET NO": "Parent ticket number",
    "SECONDARY ASSIGNED ENGINEER USER NAME": "Secondary assigned engineer name",
    "SECONDARY ASSIGNED ENGINEER EMAILID": "Secondary assigned engineer email",
    "SECONDARY ASSIGNED ENGINEER EMPID": "Secondary assigned engineer employee ID",
    "RESOLUTION PRIORITY NAME": "Resolution priority name",
    "IS MAJOR INCIDENT": "Whether ticket is a major incident",
    "IS PRIORITY CHANGEDBY WG OWNER": "Whether priority was changed by workgroup owner",
    "IS ANALYST UPDATED TICKET FROM EMAIL": "Whether analyst updated ticket from email",
    "SUB WORKGROUP NAME": "Sub workgroup name",
    "CUSTOMER ID": "Customer identifier",
    "TENANT ID": "Tenant identifier",
    "LOCATION ID": "Location identifier",
    "ASSIGNED WORKGROUP ID": "Assigned workgroup identifier",
    "LAST USER COMMUNICATION UPDATED ON": "When last user communication was updated",
    "PRIVATE LOG UPDATED ON": "When private log was last updated",
    "LAST REOPEN DATE": "Date of last reopen",
    "NO OF TIME REOPENED": "Number of times ticket was reopened",
    "LAST REOPENED BY USERID": "User ID who last reopened",
    "LAST REOPENED BY USERNAME": "User name who last reopened",
    "LAST REOPENED BY EMAILID": "Email of user who last reopened",
    "LAST REOPEN REMARK": "Remark on last reopen",
    "LAST APPROVAL REOPEN REMARK": "Last approval reopen remark",
    "LAST APPROVAL REOPEN REMARK DATE": "Date of last approval reopen remark",
    "COLOR CODE": "Color code for display or priority",
    "DEVICE HOST NAME": "Device host name",
    "IP ADDRESS": "IP address",
    "MAC ADDRESS": "MAC address",
    "MODEL NO": "Model number",
    "PURCHASE ORDER NO": "Purchase order number",
    "SERIAL NO": "Serial number",
    "WARRANTY": "Warranty information",
    "WORKORDER NAME": "Work order name",
    "NO OF DAYS": "Number of days (e.g. duration)",
    "NO OF HOURS": "Number of hours",
    "NO OF MINUTES": "Number of minutes",
}


def get_column_glossary_description(column_name: str) -> str:
    """Return glossary description for column if known, else empty string. Case-insensitive. Tries both space and underscore variants."""
    if not column_name:
        return ""
    key = str(column_name).strip().upper()
    return COLUMN_GLOSSARY.get(key) or COLUMN_GLOSSARY.get(key.replace("_", " ")) or ""
